# Keybindings and Navigation

# Pane navigation (vim-like)
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Split window
bind | split-window -h
bind - split-window -v

# Move current window (tab) forwards/backwards
bind -r N swap-window -t +1 \; select-window -t +1
bind -r P swap-window -t -1 \; select-window -t -1

bind-key -n M-o if-shell -F '#{==:#{session_name},scratch}' 'detach-client' 'display-popup -E -w 80% -h 80% -S "fg=black,bg=yellow" "tmux new-session -A -s scratch"'

# Context menu (M-q)
bind-key -n M-q display-menu -x M -y M \
    "Reset CWD"                          C "attach-session -c \"\#\{pane_current_path}\"" \
    "Rename Session"                     r "command-prompt -I #S \"rename-session '%%'\"" \
    "New Session"                        S "command-prompt -p \"New Session:\" \"new-session -A -s '%%'\"" \
    "Kill Session"                       x "kill-session" \
    "Kill Other Session(s)"              X "kill-session -a" \
    "" \
    "New Window"                         ␍ new-window \
    "Kill Window"                        k "killw"  \
    "Choose Window"                      w choose-window \
    "Previous Window"                    🡠 previous-window \
    "Next Window"                        🡢 next-window \
    "Swap Window Right"                  ↑ "swap-window -t -1" \
    "Swap Window Left"                   ↓ "swap-window -t +1" \
    "Horizontal Split"                   v "split-window -h" \
    "Vertical Split"                     s "split-window -v"  \
    "" \
    "Layout Horizontal"                  h "select-layout even-horizontal"  \
    "Layout Vertical"                    k "select-layout even-horizontal"  \
    "" \
    "Swap Pane Up"                       < "swap-pane -U" \
    "Swap Pane Down"                     > "swap-pane -D" \
    "Break Pane"                         t break-pane \
    "Join Pane"                          j "choose-window 'join-pane -h -s \"%%\"'" \
    "Rename Pane"                        R "command-prompt -p \"Pane title:\" \"select-pane -T '%%'; set-option -p allow-rename off; set-option -p allow-set-title off\"" \
    "Move Pane to Window"                M "choose-window \"move-pane -t '%%'\"" \
    "Move Pane to Session"               m "choose-tree -s \"move-pane -t '%%'\"" \
    "Reload config"                      r "source-file ~/.tmux.conf" \
    "#{?window_zoomed_flag,Unzoom,Zoom}" z "resize-pane -Z"
