# General Settings

set -g mouse on 

# set the escape key to immediately execute, for easier vim/kakoune usage within tmux.
set -sg escape-time 0

# use Ctrl-A as the hotkey
set-option -g prefix C-a

# longer history
set -g history-limit 5000

# renumber windows when a window is closed
set -g renumber-windows on

# update your terminal emulator's title with the current program
set -g set-titles on

# vi mode because it's the best!
set-window-option -g mode-keys vi

# Enable pane border titles (lightweight per-split titles)
set -g pane-border-status top
set -g pane-border-format "#{?pane_active,#[fg=white#,bg=green] [*] #{pane_title} #[default], [_] #{pane_title} }"
