set-option global tabstop 2
set-option global indentwidth 2
set-option global scrolloff 1,3

# Display line numbers
add-highlighter global/ number-lines -hlcursor
# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Add kak-bundle
source "%val{config}/bundle/kak-bundle/rc/kak-bundle.kak"
bundle-noload kak-bundle https://github.com/jdugan6240/kak-bundle

bundle fzf https://github.com/andreyorst/fzf.kak %{
  map global normal <c-p> ': fzf-mode<ret>'
}

map global insert <c-[> <esc>
