tap "1password/tap"

brew "git"
brew "gnu-sed"
brew "fzf"
brew "jq"
brew "kakoune"
brew "neovim"
brew "nvm"

cask "1password"
cask "1password-cli"
cask "cleanshot"
cask "displaylink"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "notion"
cask "obsidian"
cask "raycast"
cask "slack"
cask "sourcetree"
cask "spotify"
cask "tableplus"
cask "visual-studio-code"