[language_ids]
javascript = "javascriptreact"
typescript = "typescriptreact"

[language_server.typescript]
filetypes = ["typescript","javascript"]
roots = ["pnpm-lock.yaml","yarn.lock",".npmrc","tsconfig.json"]
command = "typescript-language-server"
args = ["--stdio"]
settings_section = "_"

[language_server.typescript.settings._]

