[language_ids]
javascript = "javascriptreact"
typescript = "typescriptreact"

[language.typescript]
filetypes = ["typescript","javascript"]
roots = ["pnpm-lock.yaml","yarn.lock",".npmrc","tsconfig.json"]
command = "node"
args = ["/Users/ryan/.config/kak-lsp/tsreact/index.js", "--stdio"]
settings_section = "_"

[language.typescript.settings._]

