[language_ids]
javascript = "javascriptreact"
typescript = "typescriptreact"

[language."typescript"]
filetypes = ["typescript","javascript"]
roots = ["pnpm-lock.yaml","yarn.lock",".npmrc","tsconfig.json"]
command = "typescript-language-server"
args = ["--stdio"]
settings_section = "_"

[language.typescript.settings._]
tsserver = {logDirectory = "/Users/ryan/Downloads/",logVerbosity = "verbose"}

